#!/usr/bin/env bash

set -euo pipefail
for partition_id in $(fca-partitions); do
    sudo mkdir -p "/mnt/${partition_id}"
    sudo mount "/dev/disk/by-uuid/${partition_id}" "/mnt/${partition_id}"
done

fca-sync
