#!/usr/bin/env bash

function show_help {
    cat << EOF
usage:

fos-rotate-passwords --old /path/to/old-password-file --new /path/to/new-password-file
EOF
}

function confirm {
    while true; do
        read -p "$* (y/n): " answer
        case $answer in
            [Yy]) return 0 ;;
            [Nn]) exit 1 ;;
        esac
    done
}

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -o|--old) old="$2"; shift ;;
        -n|--new) new="$2"; shift ;;
        *) echo "Unknown parameter: $1"; show_help; exit 1 ;;
    esac
    shift
done

for var in "old" "new"; do
    if [[ -z "${!var}" ]]; then
        echo "missing parameter --$var"
        show_help
        exit 1
    fi
done

confirm "re-encrypt all keys and PINs in $(fos-working-directory)/archive/ with password $new?"

secret_keys=$(find $(fos-working-directory)/archive/ -type f -name "secret.asc")
pins=$(find $(fos-working-directory)/archive/ -type f -name "*pin.asc")

for key in $secret_keys; do
    sq key password --batch \
    --password-file $old \
    --new-password-file $new \
    --cert-file $key \
    --output $key \
    --overwrite
done

for pin in $pins; do
    sq decrypt -q --batch \
      --password-file $old \
      $pin |\
    sq encrypt -q --batch \
      --without-signature \
      --with-password-file $new \
      --output $pin \
      --overwrite
done
