version = 0
commit_goodlist = []

[authorization."Pranav Padalkar <p.padalkar@famedly.com>"]
sign_commit = true
sign_tag = true
sign_archive = true
add_user = true
retire_user = true
audit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 1EDC 5634 B932 E8D1 41C6  81E4 968C AEF3 1959 CFAE
Comment: Pranav Padalkar <p.padalkar@famedly.com>

xjMEZykByRYJKwYBBAHaRw8BAQdAoPC9IGXncV7ZIkukCW8BCzwEiGS08r23FQPX
g1j30bHCwBEEHxYKAIMFgmcpAckFiQPCZwADCwkHCRCWjK7zGVnPrkcUAAAAAAAe
ACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmcqxiME3AfMYINu6g8tfFsl
/w0qC1L/Q4ISeNf5PucP2QMVCggCmwECHgEWIQQe3FY0uTLo0UHGgeSWjK7zGVnP
rgAAzmIBAK/tCa2/9nnkbEW69HgFXgEI9/sbbG6tLun9H3xU7S26AP4v19mq0xcA
MZoAvvPHcWx9teA/sApo8qpiEconLR2WBM0oUHJhbmF2IFBhZGFsa2FyIDxwLnBh
ZGFsa2FyQGZhbWVkbHkuY29tPsLAFAQTFgoAhgWCZykByQWJA8JnAAMLCQcJEJaM
rvMZWc+uRxQAAAAAAB4AIHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ1I+
grfn+wc+9lCbaEczT5fPk0gBIHdjdiZKNnHMWwGCAxUKCAKZAQKbAQIeARYhBB7c
VjS5MujRQcaB5JaMrvMZWc+uAABb7AEA3a+yV1TILhOkd/EFS9JmF07XJs8LMpf7
leKCLm4ktSMBAMGwsaCZ4T8x2WpuHAeG0tCO4fGl1y1RBlMWLJQqh0MEwsAoBBAW
CgCaBYJnKQIFBYMDwmcACRDIAcdhm8IfHUcUAAAAAAAeACBzYWx0QG5vdGF0aW9u
cy5zZXF1b2lhLXBncC5vcmc1SSIF7W7b3gG6gh9EbXNauBuRMP8oycBxLPsXwedf
PiQcT3BlblBHUCBDQSA8b3BlbnBncC1jYUBmYW1lZGx5LmNvbT4WIQRQsOrFBXSa
wH6a5grIAcdhm8IfHQAAppoBAMX5hCFxgFE448UipBHmlgV9bkhFlWOm07ttKqTA
3CEPAQCHae7zHSAmPfuhz0ctCuokVLTehebLsiifrCC79wyIDc4zBGcpAckWCSsG
AQQB2kcPAQEHQCENYMJ7YYr7IrMhN5QYio0wafeTeumx3DP2i7gwGShswsAGBBgW
CgB4BYJnKQHJBYkDwmcACRCWjK7zGVnPrkcUAAAAAAAeACBzYWx0QG5vdGF0aW9u
cy5zZXF1b2lhLXBncC5vcmcHUdvLvYKOaJk7czn01aDz2zYrkwg3yf/o+YC6yBGj
WAKbIBYhBB7cVjS5MujRQcaB5JaMrvMZWc+uAADMPgEA7mqwZLVvh00Ds0hG22CX
PYvONpyMTGg+Q7JwIGzTRMYBAKdRoJJkjf7pZkdZW4wklFdpnmQXjVTAGfD7grH/
RgAMzjMEZykByRYJKwYBBAHaRw8BAQdA5NTAf2STllaNuZHlGlBoduDUx6Kt0lXl
GVkcDtQFw4TCwMUEGBYKATcFgmcpAckFiQPCZwAJEJaMrvMZWc+uRxQAAAAAAB4A
IHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZwtaseyT1QG3/r/XUCAiAK+K
3kODk8g3dix3lehMGcjkApsCvqAEGRYKAG8FgmcpAckJEAL9GEHtiT8FRxQAAAAA
AB4AIHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ3uw/Qc/+/QdQ1YqUpuB
T9PNtztr6rnp4e3y0Qs8BuEgFiEEGxnTWFUhMHdiCTSlAv0YQe2JPwUAAO1OAQDr
euGXCuKDmwvheit8Trrwbm/AFOU9LVPwTO0isWFgTwEAoha73zn0xCMWje+YuYND
2vnfe4SnlR/TOx2EdC3pqAwWIQQe3FY0uTLo0UHGgeSWjK7zGVnPrgAAZpsBAPDV
4yW+ehCXsVMF6ep7EcS+TXv6z7ZMJuVz9TLKFfF2AP0Sjnb1OWbo6qrag4aSpqy3
R66YIF8yfajL+HozMHp4CM44BGcpAckSCisGAQQBl1UBBQEBB0CO+5Hiu3OhtTBo
wGCGLM0ri17MRP0YNnXig+Y/tOVgWwMBCAfCwAYEGBYKAHgFgmcpAckFiQPCZwAJ
EJaMrvMZWc+uRxQAAAAAAB4AIHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9y
Z8qvfyUU8FAdpsok7fXUnXfq4UO1DtrNQqLne/Hezdc1ApsMFiEEHtxWNLky6NFB
xoHkloyu8xlZz64AAO5eAQDYgSiT9uME1PG6IktArPSYCJ7WianmSj58uFztI/TR
ZQD+K+eekqMN6UvK9S9JRJNc/tqd5oVTyEYqI4PfPZuoNwU=
=EXz/
-----END PGP PUBLIC KEY BLOCK-----
"""

[authorization."Lukas Lihotzki <l.lihotzki@famedly.com>"]
sign_commit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 84D1 D173 50A1 8995 C0BC  FD5E 970D B544 FA96 2851
Comment: Lukas Lihotzki <l.lihotzki@famedly.com>

xjMEYtXvhxYJKwYBBAHaRw8BAQdAFpGgpcxUdzK1O/Nyk1+oXolKRyAIxfYtqfKO
hVPgrLvNJ0x1a2FzIExpaG90emtpIDxsLmxpaG90emtpQGZhbWVkbHkuY29tPsKW
BBMWCAA+FiEEhNHRc1ChiZXAvP1elw21RPqWKFEFAmLV74cCGwEFCQPCZwAFCwkI
BwIGFQoJCAsCBBYCAwECHgECF4AACgkQlw21RPqWKFEcHwD/YpPnMLYm5RgNEXtq
tDWLS5u2A+SAjWFLruUzenc0ZuwBAM2v4cERoaF8xTW/f6ieu4hkii8/SBWSev57
/Ly9giINzjMEYtXwfhYJKwYBBAHaRw8BAQdAq/qbmeQTkg4etanwnWrcoUKVBQOa
e1FtpzLsuNXzowfCwDUEGBYIACYWIQSE0dFzUKGJlcC8/V6XDbVE+pYoUQUCYtXw
fgIbAgUJA8JnAACBCRCXDbVE+pYoUXYgBBkWCAAdFiEEStENrn8rfMtLcjZBd6SC
+6dAIYIFAmLV8H4ACgkQd6SC+6dAIYLPJQEA+xA+QkRRFkguQ3jbk7eJo1Hm/vCn
ehTmb4aXsYgxhnMBAO0XueNVH0nnnXGtQayaBLIfWj+1HfO0RJ1fGQN82+0AHeAA
/iEdn+bIW00hbvYRk8eK2fdDAK9cI7CYPcdL56or2z1xAQDr3y0RTK43srL7awx+
f+qNMqU+fximXaGRD7xrr/2nDg==
=cpXD
-----END PGP PUBLIC KEY BLOCK-----
"""

[authorization."Sebastian Fleer <s.fleer@famedly.com>"]
sign_commit = true
sign_tag = true
sign_archive = true
add_user = true
retire_user = true
audit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 6AFC C218 4CF4 87AD 0567  F54E 38E7 4E64 4AE5 E3DE
Comment: Sebastian Fleer <s.fleer@famedly.com>

mDMEZXMYTRYJKwYBBAHaRw8BAQdASNVXvuKslyZzWv4klOUvB2OZaxktVm/d0cVD
3tPZ2yWI0QQfFgoAgwWCaGTmgwWJBrTYtAMLCQcJEDjnTmRK5ePeRxQAAAAAAB4A
IHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ6ttuoESmOAF6Zdq/rwtOafl
tnwkkD4SyPf7b8TukpikAxUKCAKbAQIeARYhBGr8whhM9IetBWf1TjjnTmRK5ePe
AADcOAD9EeUiw3oPVmNDs4QYGokwEoegePL7X74kLJsSjyVsCvABAIJtAXdF7dCv
QmbzsKK2qkk2F436bmJpTbW4YuYRApkMiNEEHxYKAIMFgmVzGE0FiQPCZwADCwkH
CRA4505kSuXj3kcUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5v
cmcQEYXWlmakYsOO5U+yrYu32iiCegtoQzT8zoRzsA3WMQMVCggCmwECHgEWIQRq
/MIYTPSHrQVn9U44505kSuXj3gAAVS4BANTMp5CK6Gl0MMbS70w6xtjjayAE6pqq
67sFllaAiskeAP41nPTsahIGW+Xj+tkalqOVbDHzAHOa/K9tqOyXCv5OD7QlU2Vi
YXN0aWFuIEZsZWVyIDxzLmZsZWVyQGZhbWVkbHkuY29tPojUBBMWCgCGBYJlcxhN
BYkDwmcAAwsJBwkQOOdOZErl495HFAAAAAAAHgAgc2FsdEBub3RhdGlvbnMuc2Vx
dW9pYS1wZ3Aub3JnarmrF4c5QvgLKX+VWV6VdMEsGaxOIw8S4M0E9bsqIYwDFQoI
ApkBApsBAh4BFiEEavzCGEz0h60FZ/VOOOdOZErl494AAPjuAP4xvTRO1QB2clWw
GrKZScrkEZb5PVLujqSFHEmY9R119gEAn3AcfGXani5FXI2p7F1rQuzNur5Se5Kn
2Y1/NIByQAGI6AQQFgoAmgWCZXMYigWDA8JnAAkQyAHHYZvCHx1HFAAAAAAAHgAg
c2FsdEBub3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3JnBirsvuc3xRG6VLUoqaUEn9pj
DjqQreVdzAYk1z291mMkHE9wZW5QR1AgQ0EgPG9wZW5wZ3AtY2FAZmFtZWRseS5j
b20+FiEEULDqxQV0msB+muYKyAHHYZvCHx0AAFjyAP42JMRGKC0JN5eZ74xxy/NO
fIAkxk7a42VLi2Z/6GdbmwEAu17FyfbhzkSfHdmuKIWJ371LRVZGEzGCkcRgtJJV
gQ2I1AQTFgoAhgWCaGTmgwWJBrTYtAMLCQcJEDjnTmRK5ePeRxQAAAAAAB4AIHNh
bHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ9i+Ugy/KTpXHYrrnQCwLDuqmWj1
IyuGBKl2oNY5KHBQAxUKCAKZAQKbAQIeARYhBGr8whhM9IetBWf1TjjnTmRK5ePe
AACkMQEA4KFQwsE6YHBihYQEn1CXaCEbjPcwM51SdC/i5pNEblwBAM9BV09rULAt
9aPRVdZM4Q0MWQipE6/kTWmdAF4ntpAFiMMEEBYKAHUFgmhmkr8FgwPDCn4JEMgB
x2Gbwh8dRxQAAAAAAB4AIHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ12W
KuMlaYZlWVGGl6IGGotiiVXsTkyo2RGbwTDNGO1MFiEEULDqxQV0msB+muYKyAHH
YZvCHx0AAEgZAP4vnkZbADtlAY9mL07TL3jUGRGY9i1Y0uS4jrAoX9NKggEA1LBI
DECBeWCBi3TzcVwLUu+DmhReKuQITYYatd8UIg+4MwRlcxhNFgkrBgEEAdpHDwEB
B0AAHBAQ/0a/E7nrlxxv8wBXxpv0kbrf16aSxD7eI/6O34jGBBgWCgB4BYJlcxhN
BYkDwmcACRA4505kSuXj3kcUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lh
LXBncC5vcmdZ5ucomzjdGJLumptvB0Ej6GzCwRGiVWuCyLNIHFYS/QKbIBYhBGr8
whhM9IetBWf1TjjnTmRK5ePeAABBVQEArTs0YFUBcKRaNjInlcRzABkRGi5qkVaw
6BF/RkBHxOsA/Ry3JMA/3mNVzQZivFcNLHFpPOlzqL8M5eNBYYgp2QMFiMYEGBYK
AHgFgmhk5oMFiQa02LQJEDjnTmRK5ePeRxQAAAAAAB4AIHNhbHRAbm90YXRpb25z
LnNlcXVvaWEtcGdwLm9yZ54IR+SnGFIRFOtxtxLkRpYtRWFYST9SK767GWkt4H22
ApsgFiEEavzCGEz0h60FZ/VOOOdOZErl494AAOjSAQCiUpcztdXvR8F8XBjChZAH
RPyfI4PuRvOaTdc7F1spqQD+JtGHFzUk28Gj/Gk1mF1LylgcZkEo6KjHXs5uUEvb
nwG4MwRlcxhNFgkrBgEEAdpHDwEBB0BfKg/LuGbQSX2hiVoEEXMN+bXUxehKhPsa
fAMQT82WL4kBhQQYFgoBNwWCZXMYTQWJA8JnAAkQOOdOZErl495HFAAAAAAAHgAg
c2FsdEBub3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3JnMFMk9bIuI39ivMiqxDp7ANKz
7xy1EiFvdZzeO+7IxSwCmwK+oAQZFgoAbwWCZXMYTQkQwky4PVKt6NZHFAAAAAAA
HgAgc2FsdEBub3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3JnORwPs2DJIq0/NTtcUTvn
hDKPloRadrQO1oS1V5WGc8AWIQSvJ/SP7uH+ZYg1oiTCTLg9Uq3o1gAAZzoA/18L
RjmqjyinijArkO3JdJ6i4rELoY3kFcpM07It3AFwAP9jYtS1NxCfCC/amcGlgT38
Xy60UDxpg2t8thYuSGNUDhYhBGr8whhM9IetBWf1TjjnTmRK5ePeAABOVgEA6rN9
tVchTngzXrtCeKfQQx6wknRuSI69D7Tn10PCD90BAK9QKJ+6f2nXLZZ+KoP4tfWU
tDKUTBcz/MBxH6Dpu7cDiQGFBBgWCgE3BYJoZOaDBYkGtNi0CRA4505kSuXj3kcU
AAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmf//SCcj0cplhAI
DnSa1KTh88R/kl/dTc0qNZhkgI0W1AKbAr6gBBkWCgBvBYJlcxhNCRDCTLg9Uq3o
1kcUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmc5HA+zYMki
rT81O1xRO+eEMo+WhFp2tA7WhLVXlYZzwBYhBK8n9I/u4f5liDWiJMJMuD1SrejW
AABnOgD/XwtGOaqPKKeKMCuQ7cl0nqLisQuhjeQVykzTsi3cAXAA/2Ni1LU3EJ8I
L9qZwaWBPfxfLrRQPGmDa3y2Fi5IY1QOFiEEavzCGEz0h60FZ/VOOOdOZErl494A
APgZAP4kdk+3H2qDlY/uWkDv4qJ/IR/vHAUgQiGhXMdGrfYVagEAuRdLebaop5Fw
o8gGarbUkY42FUMNdCrZi3FIrWA9Mgi4OARlcxhNEgorBgEEAZdVAQUBAQdAHLMB
S5I1/al5Jhn13mxskyhqS4jmhFWjQapZO8FWLSkDAQgHiMYEGBYKAHgFgmVzGE0F
iQPCZwAJEDjnTmRK5ePeRxQAAAAAAB4AIHNhbHRAbm90YXRpb25zLnNlcXVvaWEt
cGdwLm9yZ0ptQ6gGpLFCHN0E01ubCQSRz8hRyrDrBaHDn6oIovSRApsMFiEEavzC
GEz0h60FZ/VOOOdOZErl494AAKxmAP962RBg8vt6Jpq671pX9xEdk0lNVAH2jaj1
2hHAq0A0YgEAkE6m/2q5wUrL3ucr+fZjmAi698awDL2MHXJaM1G2Cg+IxgQYFgoA
eAWCaGTmgwWJBrTYtAkQOOdOZErl495HFAAAAAAAHgAgc2FsdEBub3RhdGlvbnMu
c2VxdW9pYS1wZ3Aub3JnWKyzNAw0q8do73gtbBMiMZk2YbgJj49TdUTHuEVoiKEC
mwwWIQRq/MIYTPSHrQVn9U44505kSuXj3gAA4L8BAPCAMb2oRlAWq+jnFZ1kio8R
dR/5C4gT0AdgMDUfmSALAQCJJxef6iXaLLrz0LrPtT5f7NuEv1nq1sQiwlbKRJB5
DQ==
=nwyh
-----END PGP PUBLIC KEY BLOCK-----
"""

[authorization."Tobias Zenk <t.zenk@famedly.com>"]
sign_commit = true
sign_tag = true
sign_archive = true
add_user = true
retire_user = true
audit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 0E2D 1E63 E225 3D85 D7F0 33F7 FDCD 523F 5C4E BFC0
Comment: Tobias Zenk <t.zenk@famedly.com>

mDMEZoLLZRYJKwYBBAHaRw8BAQdAjoFMdmwvdIALqgcpSelYA1naWc8xosFbMBTl
CdH+N6iI0QQfFgoAgwWCZoLLZQWJA8JnAAMLCQcJEP3NUj9cTr/ARxQAAAAAAB4A
IHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ8EO9jbFJc8lehV0CMEY+QtH
OOWJzVj0jtC7q20Mr0/qAxUKCAKbAQIeARYhBA4tHmPiJT2F1/Az9/3NUj9cTr/A
AABVPQEAxKVxgeoASrp+zGIoPSLj0U7GqhU3nkIzCasScXQ+4+gBAODmc5N5ntUz
X18tPPRxd3GYKJ8myMD/yiyXq1BcS0oDtCBUb2JpYXMgWmVuayA8dC56ZW5rQGZh
bWVkbHkuY29tPojUBBMWCgCGBYJmgstlBYkDwmcAAwsJBwkQ/c1SP1xOv8BHFAAA
AAAAHgAgc2FsdEBub3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3JnivUMtaO3DMeiAOj0
BVlUSLZwGeciyXl/P/kE4nyE0u4DFQoIApkBApsBAh4BFiEEDi0eY+IlPYXX8DP3
/c1SP1xOv8AAALq+AQCL/Zs1mGffcnF1/hkslopa84A2Ib4vKIFndPietvF7ZwD+
OQtflzM8x4mLLXbvR3sRKQy5eENU9rGzx1IShdLLIQy4MwRmgstlFgkrBgEEAdpH
DwEBB0CE8ziQIhUpCV/NsaNBELz6l8Y+G/jO/CLHxxEXGG9i5IjGBBgWCgB4BYJm
gstlBYkDwmcACRD9zVI/XE6/wEcUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1
b2lhLXBncC5vcmfcQJ3TI7T+G9W3Wg91d85iuvlicMdGOBQkT7MY94/r2AKbIBYh
BA4tHmPiJT2F1/Az9/3NUj9cTr/AAAAZcAEAnrbiyEeJPvhqi9cTuRlH3+rWJ2vE
Ih2sOxhLZgc3iMgA/3OVQALa0qfdY3PmJbY+3G7rxoOMJjr19ecOC0FDPKsLuDME
ZoLLZRYJKwYBBAHaRw8BAQdA71KHIIo/8Sk+551dYYU0+0k86ruDGNHltsreaTfo
5NSJAYUEGBYKATcFgmaCy2UFiQPCZwAJEP3NUj9cTr/ARxQAAAAAAB4AIHNhbHRA
bm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZxxyfHEKsvHJrn4ckMh/V4WjAp4qJM8X
nyXQCg3QFoIJApsCvqAEGRYKAG8FgmaCy2UJEJU/+wIEZeaGRxQAAAAAAB4AIHNh
bHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZwS5Bbj6tOkj5FdOqBZdzzvBGSvL
jorvwO0T3PpdEwM1FiEEVl3r6hcbJlckxJ5wlT/7AgRl5oYAAMz8AP9hTUgZBttx
L+d7U0lEmQ3IrJIUmO3Skln3c81O3eSciQEA9Z6wvsln0m1+X1pzw9+Bok8sm9cE
Srn83k+f6yvyKggWIQQOLR5j4iU9hdfwM/f9zVI/XE6/wAAA6r8A/AzCWl6WBeLT
JMPUJ7zh0/ft3vVOzntdrxklLaCzDKLPAP922Zy4lx4Yx0tyQrq4Xy93UsHf/aA0
CDvNhhDzR4psDLg4BGaCy2USCisGAQQBl1UBBQEBB0A/pSpoXHBwp+gM6hNYy8av
rLXkVS4PZs+DJnN6+p7qBgMBCAeIxgQYFgoAeAWCZoLLZQWJA8JnAAkQ/c1SP1xO
v8BHFAAAAAAAHgAgc2FsdEBub3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3JncT7OedjM
0BwCBnSeEA1TjZ3jAoZnv1V7DB/aya0ie3cCmwwWIQQOLR5j4iU9hdfwM/f9zVI/
XE6/wAAAGqwBAKqIy5FoJFv4BOBcCQw9wx8dLHRREUNaPiTdmZNnrrTJAP4mUTBx
Idn4IqJ2MfqsSND5MM7gN1/ExauZzn3AIfdzDg==
=XlQJ
-----END PGP PUBLIC KEY BLOCK-----
"""

[authorization."Morteza Zamani <m.zamani@famedly.com>"]
sign_commit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 3B25 8DB4 F57F DFCD 5E87 0A74 DB36 C16B 818E F0D4
Comment: Morteza Zamani <m.zamani@famedly.com>

mDMEZ4FbNRYJKwYBBAHaRw8BAQdAnYThWrDjmeJnwAYBA87Y6K3CZ/+6zPxe63p6
QnviHB2I0QQfFgoAgwWCZ4FbNQWJA8JnAAMLCQcJENs2wWuBjvDURxQAAAAAAB4A
IHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ3/F1a59x6PTyxYX4e4drmOU
fOK5sxunop3VJo/PZwPTAxUKCAKbAQIeARYhBDsljbT1f9/NXocKdNs2wWuBjvDU
AADclQD+I2ferjOBH4EZ8V4FR7Uu9HT218nPZgJTi6IjV+NeMAwA/3G9DQ+ex5N8
r2o8yJyj4Cvn2yAzXtN6VW4WTEs7XP8GtCVNb3J0ZXphIFphbWFuaSA8bS56YW1h
bmlAZmFtZWRseS5jb20+iNQEExYKAIYFgmeBWzUFiQPCZwADCwkHCRDbNsFrgY7w
1EcUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmd8+C3r+56g
qw3EjmOsTS9FSfOYybRGUFkreWUxlHyePwMVCggCmQECmwECHgEWIQQ7JY209X/f
zV6HCnTbNsFrgY7w1AAAiNEBALSckSzsqZMNSrSTi0bv7Jz5y/GQ4eMTnBdlBaP4
cePdAPwInJ+HDv/Cfi3733MwZI0BG746zJgpI+lMU5wgcSFJCojoBBAWCgCaBYJn
gVtxBYMDwmcACRDIAcdhm8IfHUcUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1
b2lhLXBncC5vcmexSmnX/CPgcQGpdff+uzQri36gB4mCkp8lfF8tSd2wsyQcT3Bl
blBHUCBDQSA8b3BlbnBncC1jYUBmYW1lZGx5LmNvbT4WIQRQsOrFBXSawH6a5grI
Acdhm8IfHQAAKgwA/jkTLBQiWoqlWdlg16oKiwnOGtddwDlsgKh1RsBQ09TxAPsG
pjbwmlt4jiXG/55S8F5cOSMlE0/f/qJNiwgdEMkrAbgzBGeBWzUWCSsGAQQB2kcP
AQEHQLKMFbgeq9iIB6tKVTHNaFj2oK4+8wuM2pEnsFHKx02KiQGFBBgWCgE3BYJn
gVs1BYkDwmcACRDbNsFrgY7w1EcUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1
b2lhLXBncC5vcmd/RX+KF099emlmNxgB4zodJTDeDfZvD14b9A163qcayQKbIL6g
BBkWCgBvBYJngVs1CRCD09zaDhsFBEcUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5z
ZXF1b2lhLXBncC5vcmelibHgTc8ZUkTnxKuEHwF3tozEecNT40aieZVc5+mobxYh
BA+x0ZLeOaB+cRZND4PT3NoOGwUEAAChygEAklDlPomTwuok60W/r9BtYcI8Cnb0
6GzoAeJatayTq1UA/1Sis0qGs0QBYEX3jRwSu7fu3W2mMKoIgMFN8B8BkjABFiEE
OyWNtPV/381ehwp02zbBa4GO8NQAALJJAP0etfWPjDNzRi441fNjEFzo+E39alMb
azO1NTU70Nr/bQEA2tJPErvduVewHngzV/B46HzlGyZ/J3BUBg4DpdYthQa4MwRn
gVs1FgkrBgEEAdpHDwEBB0D1sieo/LMfuUMhgboE3RzEp1HDiyxrH5ZeaTCGMDiU
WIkBhQQYFgoBNwWCZ4FbNQWJA8JnAAkQ2zbBa4GO8NRHFAAAAAAAHgAgc2FsdEBu
b3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3JnGL17/dYPT2bFk4fjyBG8JYM8GS+tvQOG
vXMREFFv8dICmwK+oAQZFgoAbwWCZ4FbNQkQP1IrZTjUMytHFAAAAAAAHgAgc2Fs
dEBub3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3Jn2CfXQrDX1bbn4j91qri0KWyagROW
6x208/QSEzeqdU0WIQTTORy11YpID4OoVFc/UitlONQzKwAAApQA/1995Sp/fYdL
KfOSiTeeJtAiE0njRJNrbCktataqdeOSAQDNuOskrK732+lrpD3vFmVTeUAHgEOv
S3GX/YTjW3RmBhYhBDsljbT1f9/NXocKdNs2wWuBjvDUAABGDgEAg1O/CICbdOhq
GHpRFtuk6hwQ86qkmuCY83ZcwV0fcoAA/15pODJpaCDrwgp575ZoVvfUbvGdDEyd
Fm99Sf0GDZ4CuDgEZ4FbNRIKKwYBBAGXVQEFAQEHQAo3t94nXHWPyFIsf8Q7AmK3
3WNdXZDZyEuu6nc5X4VkAwEIB4jGBBgWCgB4BYJngVs1BYkDwmcACRDbNsFrgY7w
1EcUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmdBamd5dwsf
xnVcd9mq8iEqy+/G2gHs7ncQOo73b2PXoQKbDBYhBDsljbT1f9/NXocKdNs2wWuB
jvDUAAAAYAEA7nmJh/oQXWLzaBfSqEQ9Ec/sbbh/MKpRKC8ETWg55pkBAPWh0HzU
YSiqKkhG160v2/A1IQxRu+iRFnvJlVjuI8wL
=NOq/
-----END PGP PUBLIC KEY BLOCK-----
"""

[authorization."Artur Choynacki-Piotrowski <a.choynacki-piotrowski@famedly.com>"]
sign_commit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 4AF6 BD92 4606 CCA5 B8FE  1234 CE9A 4928 3D03 0717
Comment: Artur Choynacki-Piotrowski <a.choynacki-piotrowski@fame

xjMEZ6tKvRYJKwYBBAHaRw8BAQdA134eE5DvWSa6xpp9HTWu/kvXbLu82/5z5J47
qK/2oETCwBEEHxYKAIMFgmerSr0FiQPCZwADCwkHCRDOmkkoPQMHF0cUAAAAAAAe
ACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmdfVk+0KDHaO4z+nk6BvTRr
fO0IWDdqV5rHQcpdPaVHOgMVCggCmwECHgEWIQRK9r2SRgbMpbj+EjTOmkkoPQMH
FwAAkbEA+wa/VIniI7MdGwEmFhAzHbX0NNKygQDJjaYl0PDvt4NGAQCqlhpRE7CN
4XixJyVa4NXSQCViqHb/qz+pCN/t1iUrB80/QXJ0dXIgQ2hveW5hY2tpLVBpb3Ry
b3dza2kgPGEuY2hveW5hY2tpLXBpb3Ryb3dza2lAZmFtZWRseS5jb20+wsAUBBMW
CgCGBYJnq0q9BYkDwmcAAwsJBwkQzppJKD0DBxdHFAAAAAAAHgAgc2FsdEBub3Rh
dGlvbnMuc2VxdW9pYS1wZ3Aub3Jn6Q1OWwUJKxdZ9GX0RIaP1FciKrlyNN3udEbl
2MlfCEcDFQoIApkBApsBAh4BFiEESva9kkYGzKW4/hI0zppJKD0DBxcAAIugAP4m
CqZ+AaBZWMv+HZoQ1lVCD2Km81TcNwaP4kCQz1/qZwD7Bnpab0TERqo4YCVUm/o4
Mrv5jc94hsWbEF0qiw/6MQ3CwCgEEBYKAJoFgmerSvkFgwPCZwAJEMgBx2Gbwh8d
RxQAAAAAAB4AIHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ9yqkGMCLo/W
tKpRDz3QjUAHH8MUHjFYNITqa0OlYuZvJBxPcGVuUEdQIENBIDxvcGVucGdwLWNh
QGZhbWVkbHkuY29tPhYhBFCw6sUFdJrAfprmCsgBx2Gbwh8dAACTewD/dZ3MrZu7
kKzIgv8fAdv0SoPTEqz3ezGaNu2ACXCAJhsBAMa4kKcBU3DOBTXNBebDNgo78/th
wPR64eL5YQOZHrsCzjMEZ6tKvRYJKwYBBAHaRw8BAQdAeEQzi40ahl2eB/7ep6XN
KDZMb2rETMO36Ci7EoK5AZPCwMUEGBYKATcFgmerSr0FiQPCZwAJEM6aSSg9AwcX
RxQAAAAAAB4AIHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ85YZz6wx5Mh
tqXGX0hXBV6lMc55gG2Qxj8jZf2+7timApsCvqAEGRYKAG8FgmerSr0JEMUOY1cc
1pV4RxQAAAAAAB4AIHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ6s0ce7i
texZthjMsxjrAlu9EQXs8n3B6RJiLwnpc+3yFiEEgH/BbsZ6HFJyMIaixQ5jVxzW
lXgAAFHBAP9os3nNP4d4JP1nIuIWwYGTbP+zXg4NohqxqtVu7sj3ZgD/WepODIsj
cqmPo+w/zgMGOZrHv1ktC5e+L7qzDAJ8kQgWIQRK9r2SRgbMpbj+EjTOmkkoPQMH
FwAArFsBALd51WKtLk0cwjvTaINd284//hBcUCFOvHb6Df0MIrJhAP49ZSvjQhmE
0NLbgNYD9eEzj1ABuPjMcKS5JI/sx0V7A84zBGerSr0WCSsGAQQB2kcPAQEHQIw0
cwRslr1FPT1CWeKcwTukbmB4Pihqmv3DmEa56whYwsDFBBgWCgE3BYJnq0q9BYkD
wmcACRDOmkkoPQMHF0cUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBn
cC5vcmdE460cQueKHT7cSRbiAJEYMa7vgosK7wFNUKlJY1PzwgKbIL6gBBkWCgBv
BYJnq0q9CRA1aTx4OvDd40cUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lh
LXBncC5vcmc3MIkRofIPDwQ/B2hWAGd/yoZyP429J5w1f4M9KByq3BYhBJDG/WjO
f124hBusDDVpPHg68N3jAAACEAD7BYMQbYkQKfBkt+qS4kn82L88vwWcwXALryvc
Ll5CfcsA/iMw02IcHHJMvWTWslYqK0AXGxMH9NcKootrkQFBWygJFiEESva9kkYG
zKW4/hI0zppJKD0DBxcAAB+rAQCEOccYn4/GuIt4XtqOXQjeKlFwAZHeXuHgDRuV
flHRxQD8DgpKOVCwFXWnep2xmQPDtjKsJUvXOJTVWsS4iiReaQjOOARnq0q9Egor
BgEEAZdVAQUBAQdAnYDVUeAhsgBiryaS8jsP0haHuu74KPYNTnxSx3/es2QDAQgH
wsAGBBgWCgB4BYJnq0q9BYkDwmcACRDOmkkoPQMHF0cUAAAAAAAeACBzYWx0QG5v
dGF0aW9ucy5zZXF1b2lhLXBncC5vcmfpbDAO1DnrjXf2ZZI1VthjbZ1wXK5qTlAa
AFZ8PsqF8gKbDBYhBEr2vZJGBsyluP4SNM6aSSg9AwcXAABjlAEA33jJ1J0wCK8u
zElo1wX4sL3juA3un6v+HyB/5R7oukoBALoRmE9K7RQCs1mamwE9jdsJErriff3I
FMYxT0MiMAQJ
=Z0Np
-----END PGP PUBLIC KEY BLOCK-----
"""

[authorization."Modar Rostom <m.rostom@famedly.com>"]
sign_commit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 05FF 6989 5E93 8C6F FFED  7D8A D877 E93A A5C4 3979
Comment: Modar Rostom <m.rostom@famedly.com>

xjMEaAeQ2BYJKwYBBAHaRw8BAQdAkgfINrNoJVk/02RDO85OAvncWjOA+4jtRvpQ
JsXZglDCwBEEHxYKAIMFgmgHkNgFiQPCZwADCwkHCRDYd+k6pcQ5eUcUAAAAAAAe
ACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmf5ew+83TfoKAakAXaI/NR1
XdSk+O7QooxSpryxEB/jzgMVCggCmwECHgEWIQQF/2mJXpOMb//tfYrYd+k6pcQ5
eQAAN1IBANTifj4PRN1LGhJNyRs7JXNKxeNtvftQFWwNGUcUJ7/eAPwJx+IPPHeQ
hdU+QFyEpqa96q0Pmxyzd/ksl94k7KHVAM0jTW9kYXIgUm9zdG9tIDxtLnJvc3Rv
bUBmYW1lZGx5LmNvbT7CwBQEExYKAIYFgmgHkNgFiQPCZwADCwkHCRDYd+k6pcQ5
eUcUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmf17jcC2A2u
HfRho+1zZVNkxkcd9d77NHFRtfJyFic3xAMVCggCmQECmwECHgEWIQQF/2mJXpOM
b//tfYrYd+k6pcQ5eQAAEDUBAM8nRJSbxnoit2Hi/6Ia/sWd9RcZEPPzW/yy2qbE
GpgKAQD3HqqevuRS2mTO7gM9Z8gB6esdgPwQUsAZVyxWTN+gAMLAKAQQFgoAmgWC
aAeRFAWDA8JnAAkQyAHHYZvCHx1HFAAAAAAAHgAgc2FsdEBub3RhdGlvbnMuc2Vx
dW9pYS1wZ3Aub3JnQVB7tIDlw2NM2CkbfaiZsb/wMQVj7BrRdvLECBeJsMwkHE9w
ZW5QR1AgQ0EgPG9wZW5wZ3AtY2FAZmFtZWRseS5jb20+FiEEULDqxQV0msB+muYK
yAHHYZvCHx0AAMzBAP9v//7rQnzokijavI+slG/1l8/MAo1GOmR5HzVmafeCkAEA
15702g3voZAaS3a412TAlVPHQXa9Vp58VumsCytosg3OMwRoB5DYFgkrBgEEAdpH
DwEBB0Cz4GazhApvaYgZgfuyP75q8QqpSODHINNJVIFRXPdoLMLAxQQYFgoBNwWC
aAeQ2AWJA8JnAAkQ2HfpOqXEOXlHFAAAAAAAHgAgc2FsdEBub3RhdGlvbnMuc2Vx
dW9pYS1wZ3Aub3JnaGoEpJaE1R2zeMpuP3kWqAFIKuVgGdrmKe0VGcAewV0CmyC+
oAQZFgoAbwWCaAeQ2AkQkHjzxaXETBNHFAAAAAAAHgAgc2FsdEBub3RhdGlvbnMu
c2VxdW9pYS1wZ3Aub3JnEktGwFnEIRmiivVgIkRIT5LbOPOAShOrKWLqNy13HZoW
IQQb57CoRaKGBH0BjF6QePPFpcRMEwAAWkABANaS/KJBVCrmP3TSUyMHk6/99ztL
sE3SOdDzAFkWlb03AP4vAytKNkxR7Y7oICOzVAdmMA+1Wd6D3bBLO2WMlIQBDRYh
BAX/aYlek4xv/+19ith36TqlxDl5AADTiAEA5Ygh7iT3POyCJN7HvqF7WA+Deq3L
Rga/92oEWMo7QoQA/3LDUsDc7jV7dQ0eMHgMrbixNTIHBlYJ2YzkIbRU3a4HzjME
aAeQ2BYJKwYBBAHaRw8BAQdA7hzuidqbC7Cb1VvEqzU4IReDnov+biy0kU/CXvzO
9TvCwMUEGBYKATcFgmgHkNgFiQPCZwAJENh36TqlxDl5RxQAAAAAAB4AIHNhbHRA
bm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZyioEOSn1XlkAU78GQlmmU3xqVhE/wPQ
KTXtdrptYerjApsCvqAEGRYKAG8FgmgHkNgJEKIHL9NwLBg5RxQAAAAAAB4AIHNh
bHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ9FC+ymL3Dvu9NqA1m3SLNS6RNpB
KamKkhJV3ZbrFxdcFiEEuJ0lrBvxLlXzIGzGogcv03AsGDkAAIA4AQC9UwDHCgdR
9NsNW+Asm10YAyrauMcfzAAyJPyA1ZgF9QEA8Afr74Pcp1JDoGBCzeJ2MEbwVc6G
hJ+J39dDSV3WKw0WIQQF/2mJXpOMb//tfYrYd+k6pcQ5eQAAA7wBAI9q4byDm0DC
wp8CRv3xigxJmt5B+hK4wFRnnEYm+l0HAP9rfhEFRz9iUVuNKR8hBgwL2lghqHgM
VXJS2rzwVtxUCc44BGgHkNgSCisGAQQBl1UBBQEBB0CSZOVYEpeAMUyryIVa62gg
29rHxBf5xT99i80V9l2QTAMBCAfCwAYEGBYKAHgFgmgHkNgFiQPCZwAJENh36Tql
xDl5RxQAAAAAAB4AIHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ/TRExuT
7dlaQJVsFMHuZ+rDXJebq5fUF0PrX9MGPzTfApsMFiEEBf9piV6TjG//7X2K2Hfp
OqXEOXkAAGIKAP9GBZCUgUEPhdBcD4Q8lCA7LMyD6JScDPkv1Owe6VwHWAD/QkyZ
6VQGATtq8N/X4hW9OnCcPQRRu5mgFJ3NlD5aPwQ=
=D2Bh
-----END PGP PUBLIC KEY BLOCK-----
"""
