version = 0
commit_goodlist = []

[authorization."Lars Kaiser <lars@kaiser.yt>"]
sign_commit = true
sign_tag = true
sign_archive = true
add_user = true
retire_user = true
audit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: E992 B67A FB37 C7E3 DF2C  7C7C 4F21 96E8 14E5 50E1
Comment: Lars Kaiser <emperor@entropia.de>
Comment: Lars Kaiser <emperor@kaiser.yt>
Comment: Lars Kaiser <l.kaiser@famedly.com>
Comment: Lars Kaiser <lars@kaiser.yt>

xjMEYLPffhYJKwYBBAHaRw8BAQdAeNmE48v4ipkTazfvYZyaQIJiK31ww6ZrHS6Z
bWHJjrjNIUxhcnMgS2Fpc2VyIDxlbXBlcm9yQGVudHJvcGlhLmRlPsKWBBMWCgA+
AhsBBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAFiEE6ZK2evs3x+PfLHx8TyGW6BTl
UOEFAmS39yIFCQfGfpgACgkQTyGW6BTlUOGDLwEAgcMoeeyMbJAuWY5clGUeBkNo
N0+mTBnMX5sfirUac8QA/juQ9KCdUb+bCyqQHP0hQ1kLRw+tQzvRIxBTmkJ8+vgF
wpYEExYKAD4CGwEFCwkIBwMFFQoJCAsFFgIDAQACHgECF4AWIQTpkrZ6+zfH498s
fHxPIZboFOVQ4QUCYrLQEQUJBCimfwAKCRBPIZboFOVQ4RXAAP0RZ4rEZeuXWXC4
7FZX3peH8dpWtWLi7yxyMTx9PbEdHwEAyTtsqw6eMOe1JuVPEgsS17fYYTXMP9ul
urOj/K/5+QLClgQTFgoAPgIbAQULCQgHAwUVCgkICwUWAgMBAAIeAQIXgBYhBOmS
tnr7N8fj3yx8fE8hlugU5VDhBQJgyLFrBQkCPofQAAoJEE8hlugU5VDh8MUBAIVH
llQUlP8mICqK2lIPgy8UGqheTF3RwMQgmfIRWOjkAQCYSQAePHblJhFTh5nGANdS
GQ1MpDTDv/jQ4zoerBjmAMKQBBMWCgA4FiEE6ZK2evs3x+PfLHx8TyGW6BTlUOEF
AmCz4XsCGwEFCwkIBwMFFQoJCAsFFgIDAQACHgECF4AACgkQTyGW6BTlUOHxvAD/
Wf2/t1pzdZ0f0Lh68bMpCiDTibpfxHq5SzWv0XvdLxAA/1OVa+HTsLqSAheKT/At
+f71EU1wb6YSxClK0AGW6i4OzR9MYXJzIEthaXNlciA8ZW1wZXJvckBrYWlzZXIu
eXQ+wpYEExYKAD4CGwEFCwkIBwMFFQoJCAsFFgIDAQACHgECF4AWIQTpkrZ6+zfH
498sfHxPIZboFOVQ4QUCZLf3IgUJB8Z+mAAKCRBPIZboFOVQ4clSAQDdSXatlnuo
Gct4qF/jNtFW4tEZC4poqhDm0gwush0vswEAwWdndDRe2tLaCCBykdLEJ0K4Fo+V
jXMwPJvr6Xf9GwfClgQTFgoAPgIbAQULCQgHAwUVCgkICwUWAgMBAAIeAQIXgBYh
BOmStnr7N8fj3yx8fE8hlugU5VDhBQJistAQBQkEKKZ/AAoJEE8hlugU5VDhENgB
AOwTsUAA4iy+QeRuYxIW5xEPvijYWT9ztfrKm7xeAPBIAP9mmk69tlZDZzAqldu4
3GJx/EAV+zu9622PgsLu8Zv/DsKWBBMWCgA+AhsBBQsJCAcDBRUKCQgLBRYCAwEA
Ah4BAheAFiEE6ZK2evs3x+PfLHx8TyGW6BTlUOEFAmDIsWsFCQI+h9AACgkQTyGW
6BTlUOEhMgD/YVuz/jbCJLRLzV6M9GB2WPfJXC7SqE6SoZoB8oi6pp8BAPzMYXBy
lrPt4JoqeIGUSEUqcPiIYgt5eP6xpVBLA5cPwpAEExYKADgWIQTpkrZ6+zfH498s
fHxPIZboFOVQ4QUCYLPhKQIbAQULCQgHAwUVCgkICwUWAgMBAAIeAQIXgAAKCRBP
IZboFOVQ4SPQAPwO4RxVcivQbkKo7rSiIRtmccleDfGQj4v16VGXdJtbMAD/QRKU
mh9tltXgHTHcTZyUiU3hBvjI6E8ZVenNoShhog7NIkxhcnMgS2Fpc2VyIDxsLmth
aXNlckBmYW1lZGx5LmNvbT7ClgQTFgoAPgIbAQULCQgHAwUVCgkICwUWAgMBAAIe
AQIXgBYhBOmStnr7N8fj3yx8fE8hlugU5VDhBQJkt/ciBQkHxn6YAAoJEE8hlugU
5VDhNWEA/1DrhmArhOGbbCHMMrEYDpmXy1Z6/QTv2+rpLHAC6bWZAQC0Rtcqvz7o
vNOfeUftUVy4lVGt2gI3fU0UcvHZ84lFBsKWBBMWCgA+FiEE6ZK2evs3x+PfLHx8
TyGW6BTlUOEFAmKy0JoCGwEFCQQopn8FCwkIBwMFFQoJCAsFFgIDAQACHgECF4AA
CgkQTyGW6BTlUOEsoQD/ejzN4h5AObXACkC9SeXtncdB7dC59cRBCi0zlDlU+SoA
/2czpZmHZSQwVETZ8s7MLzbtcqY7jblA4Z9yMeQuEkYCzRxMYXJzIEthaXNlciA8
bGFyc0BrYWlzZXIueXQ+wpkEExYKAEECGwEFCwkIBwMFFQoJCAsFFgIDAQACHgEC
F4ACGQEWIQTpkrZ6+zfH498sfHxPIZboFOVQ4QUCZLf3FgUJB8Z+mAAKCRBPIZbo
FOVQ4YYCAP4pZFXf8X0XeTR0+PxfAIdErLkfr198qEmGh+ZN637NmQD+PrVmuebj
ihpmsVzXBVFl6A5vEHep4B/MJ7KR07NIhQfCmQQTFgoAQQIbAQULCQgHAwUVCgkI
CwUWAgMBAAIeAQIXgAIZARYhBOmStnr7N8fj3yx8fE8hlugU5VDhBQJiss/9BQkE
KKZ/AAoJEE8hlugU5VDhxSABAK3h6iBJ9kBWEjzE1DdMG2w5Bo70VEZ5uXOIeNBY
6WAOAQCZQ+VPekftcvQnpzi7YF2Cq8+hhhHpoBdN3kHOWRC3CsKZBBMWCgBBAhsB
BQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAhkBFiEE6ZK2evs3x+PfLHx8TyGW6BTl
UOEFAmDIsU4FCQI+h9AACgkQTyGW6BTlUOFklwD/VmLODznwgWgIxdks5kUNKRcr
UX4jatI57Us+6T2wTxgA/1etlb9LQPs+V4TELEfetAhvv4EbVEhFKYrJw9pEjSIO
wpMEExYKADsCGwEFCwkIBwMFFQoJCAsFFgIDAQACHgECF4AWIQTpkrZ6+zfH498s
fHxPIZboFOVQ4QUCYLPiMQIZAQAKCRBPIZboFOVQ4SVmAP9aoIQ0GspflRwIymmU
tzuqoVSpptQTXxMNchf2Njj88AD/asqkF1/aGNehMaUn/+WGjuQjrNFYpbkgg9Cx
0kaHTQ/OMwRgs+ALFgkrBgEEAdpHDwEBB0AY81Nv8kqedFwo5LXo75b13pnxB7tk
l8NFdSceUCZMZMLANQQYFgoAJgIbAhYhBOmStnr7N8fj3yx8fE8hlugU5VDhBQJk
t/czBQkHxn4oAIEJEE8hlugU5VDhdiAEGRYKAB0WIQTEQC8SQviY5OSvply7lzBK
FrxdzwUCYLPgCwAKCRC7lzBKFrxdzzBhAP9FreXovlAPm2oKfQlzcdtvhUySo77x
LCJmBAzUiAo4OgEAyP6el4dLwRPyjteZaAhTQaZe3nxkOxEfLrrWYp4k+w9C0AD/
fW2d6W1dXQ7BYfBGBpkVRr7o5ahB8SVpyWxv9Sq7ICMA/2vsNVd2TuOmd7Zuk3s+
EWxCbn92aJS6FGtMeoO1MswIwsA1BBgWCgAmAhsCFiEE6ZK2evs3x+PfLHx8TyGW
6BTlUOEFAmKy0FwFCQQBGVEAgQkQTyGW6BTlUOF2IAQZFgoAHRYhBMRALxJC+Jjk
5K+mXLuXMEoWvF3PBQJgs+ALAAoJELuXMEoWvF3PMGEA/0Wt5ei+UA+bagp9CXNx
22+FTJKjvvEsImYEDNSICjg6AQDI/p6Xh0vBE/KO15loCFNBpl7efGQ7ER8uutZi
niT7DzwiAQCXVGZrcStVZxJm1ti1BUJ+HI133j6egHjyp7oAGhoH4gEAkhjvOGqG
6FBb3CIBnHvXtDzpdl0e/ag4B2QJNTSD+Qc=
=KurN
-----END PGP PUBLIC KEY BLOCK-----
"""

[authorization."Lukas Lihotzki <l.lihotzki@famedly.com>"]
sign_commit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 84D1 D173 50A1 8995 C0BC  FD5E 970D B544 FA96 2851
Comment: Lukas Lihotzki <l.lihotzki@famedly.com>

xjMEYtXvhxYJKwYBBAHaRw8BAQdAFpGgpcxUdzK1O/Nyk1+oXolKRyAIxfYtqfKO
hVPgrLvNJ0x1a2FzIExpaG90emtpIDxsLmxpaG90emtpQGZhbWVkbHkuY29tPsKW
BBMWCAA+FiEEhNHRc1ChiZXAvP1elw21RPqWKFEFAmLV74cCGwEFCQPCZwAFCwkI
BwIGFQoJCAsCBBYCAwECHgECF4AACgkQlw21RPqWKFEcHwD/YpPnMLYm5RgNEXtq
tDWLS5u2A+SAjWFLruUzenc0ZuwBAM2v4cERoaF8xTW/f6ieu4hkii8/SBWSev57
/Ly9giINzjMEYtXwfhYJKwYBBAHaRw8BAQdAq/qbmeQTkg4etanwnWrcoUKVBQOa
e1FtpzLsuNXzowfCwDUEGBYIACYWIQSE0dFzUKGJlcC8/V6XDbVE+pYoUQUCYtXw
fgIbAgUJA8JnAACBCRCXDbVE+pYoUXYgBBkWCAAdFiEEStENrn8rfMtLcjZBd6SC
+6dAIYIFAmLV8H4ACgkQd6SC+6dAIYLPJQEA+xA+QkRRFkguQ3jbk7eJo1Hm/vCn
ehTmb4aXsYgxhnMBAO0XueNVH0nnnXGtQayaBLIfWj+1HfO0RJ1fGQN82+0AHeAA
/iEdn+bIW00hbvYRk8eK2fdDAK9cI7CYPcdL56or2z1xAQDr3y0RTK43srL7awx+
f+qNMqU+fximXaGRD7xrr/2nDg==
=cpXD
-----END PGP PUBLIC KEY BLOCK-----
"""

[authorization."Sammy <s.yilmaz@famedly.com>"]
sign_commit = true
sign_tag = true
sign_archive = true
add_user = true
retire_user = true
audit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 65CA CC15 5310 7A22 B5CD  D696 BF4B 5516 695A 5D16
Comment: Samantha Yilmaz <s.yilmaz@famedly.com>

mDMEZJ15GxYJKwYBBAHaRw8BAQdACB7tQYuiT0rY+uJjx0GyZcq9jYEYKj/3B9EC
8FhOK8i0JlNhbWFudGhhIFlpbG1heiA8cy55aWxtYXpAZmFtZWRseS5jb20+iJQE
ExYKADwCGwEECwkIBwQVCgkIBRYCAwEAAh4BAheAFiEEZcrMFVMQeiK1zdaWv0tV
FmlaXRYFAmZv9XwFCQWU42EACgkQv0tVFmlaXRYLeQD+KN1ojmw7ya9KBtkKKjNn
Wqitl+0ZAZcJOesvIT/H3ZwA/21y6Gl1UQ8veYvKpW3YDUplhtWOgu3s1nNTqAnB
L84BuDMEZJ151xYJKwYBBAHaRw8BAQdA3nRqkCfb5NUhvuooupO/QqB3E/WvTSUt
MMywKLsymBiI9QQYFgoAJgIbAhYhBGXKzBVTEHoitc3Wlr9LVRZpWl0WBQJmb+8D
BQkFlNwsAIF2IAQZFgoAHRYhBO9naA56SZlylEVnu8mTVawBvHV1BQJknXnXAAoJ
EMmTVawBvHV1ct8A/R3XOo0Y5IV4JYtv7mV3oIo2nSO8iMPnTeQ5i3Zr6V8pAP9F
3wPjUCy8He4T0G8UoQAm/NPbYuJg91+TPb+ov840BAkQv0tVFmlaXRYBNAD/atj1
3e3PuoDbpH9Te3SfgBfxHUtTiDdOEKOTYk4GsaQBALgj5QcLA1jNSDYvSeJCLi0J
ooAagF3BRdY94BANKIsLuDMEZJ16SxYJKwYBBAHaRw8BAQdA603LnFifaLWxeeMW
Z5i7UHzt3YktdwUQZSeaNuLnnsuIfgQYFgoAJgIbIBYhBGXKzBVTEHoitc3Wlr9L
VRZpWl0WBQJmb+8RBQkFlNu4AAoJEL9LVRZpWl0W7KYA/j2FRfcEXX4ps1Ae0keW
+1LdK+atAIy1uR/mnNzDrjHoAP9xErpM5jMJSfsA5MGrK4DINAwGbdnyzhWMRocn
KrpFBrg4BGSdegMSCisGAQQBl1UBBQEBB0ByCNp9fAVuXF+9MoKf7zlIZ1vZNWzG
Ed3ri5ozzxlgOAMBCAeIfgQYFgoAJgIbDBYhBGXKzBVTEHoitc3Wlr9LVRZpWl0W
BQJmb+8RBQkFlNwAAAoJEL9LVRZpWl0WEecA/iCumzaaScaTDVajCjygyoSJY0lq
3jrIzXPIC/mH+s7NAQCEkt1Qj44zoyF88qPqazDDDZmqcVVNvzc6pdiCBn02Cw==
=IRtC
-----END PGP PUBLIC KEY BLOCK-----
"""

[authorization."Sebastian Fleer"]
sign_commit = true
sign_tag = true
sign_archive = true
add_user = true
retire_user = true
audit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 6AFC C218 4CF4 87AD 0567  F54E 38E7 4E64 4AE5 E3DE
Comment: Sebastian Fleer <s.fleer@famedly.com>

xjMEZXMYTRYJKwYBBAHaRw8BAQdASNVXvuKslyZzWv4klOUvB2OZaxktVm/d0cVD
3tPZ2yXCwBEEHxYKAIMFgmVzGE0FiQPCZwADCwkHCRA4505kSuXj3kcUAAAAAAAe
ACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmcQEYXWlmakYsOO5U+yrYu3
2iiCegtoQzT8zoRzsA3WMQMVCggCmwECHgEWIQRq/MIYTPSHrQVn9U44505kSuXj
3gAAVS4BANTMp5CK6Gl0MMbS70w6xtjjayAE6pqq67sFllaAiskeAP41nPTsahIG
W+Xj+tkalqOVbDHzAHOa/K9tqOyXCv5OD80lU2ViYXN0aWFuIEZsZWVyIDxzLmZs
ZWVyQGZhbWVkbHkuY29tPsLAFAQTFgoAhgWCZXMYTQWJA8JnAAMLCQcJEDjnTmRK
5ePeRxQAAAAAAB4AIHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ2q5qxeH
OUL4Cyl/lVlelXTBLBmsTiMPEuDNBPW7KiGMAxUKCAKZAQKbAQIeARYhBGr8whhM
9IetBWf1TjjnTmRK5ePeAAD47gD+Mb00TtUAdnJVsBqymUnK5BGW+T1S7o6khRxJ
mPUddfYBAJ9wHHxl2p4uRVyNqexda0Lszbq+UnuSp9mNfzSAckABzjMEZXMYTRYJ
KwYBBAHaRw8BAQdAXyoPy7hm0El9oYlaBBFzDfm11MXoSoT7GnwDEE/Nli/CwMUE
GBYKATcFgmVzGE0FiQPCZwAJEDjnTmRK5ePeRxQAAAAAAB4AIHNhbHRAbm90YXRp
b25zLnNlcXVvaWEtcGdwLm9yZzBTJPWyLiN/YrzIqsQ6ewDSs+8ctRIhb3Wc3jvu
yMUsApsCvqAEGRYKAG8FgmVzGE0JEMJMuD1SrejWRxQAAAAAAB4AIHNhbHRAbm90
YXRpb25zLnNlcXVvaWEtcGdwLm9yZzkcD7NgySKtPzU7XFE754Qyj5aEWna0DtaE
tVeVhnPAFiEEryf0j+7h/mWINaIkwky4PVKt6NYAAGc6AP9fC0Y5qo8op4owK5Dt
yXSeouKxC6GN5BXKTNOyLdwBcAD/Y2LUtTcQnwgv2pnBpYE9/F8utFA8aYNrfLYW
LkhjVA4WIQRq/MIYTPSHrQVn9U44505kSuXj3gAATlYBAOqzfbVXIU54M167Qnin
0EMesJJ0bkiOvQ+059dDwg/dAQCvUCifun9p1y2WfiqD+LX1lLQylEwXM/zAcR+g
6bu3Aw==
=L0Me
-----END PGP PUBLIC KEY BLOCK-----
"""

[authorization."Tobias Zenk <t.zenk@famedly.com>"]
sign_commit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 0E2D 1E63 E225 3D85 D7F0 33F7 FDCD 523F 5C4E BFC0
Comment: Tobias Zenk <t.zenk@famedly.com>

mDMEZoLLZRYJKwYBBAHaRw8BAQdAjoFMdmwvdIALqgcpSelYA1naWc8xosFbMBTl
CdH+N6iI0QQfFgoAgwWCZoLLZQWJA8JnAAMLCQcJEP3NUj9cTr/ARxQAAAAAAB4A
IHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ8EO9jbFJc8lehV0CMEY+QtH
OOWJzVj0jtC7q20Mr0/qAxUKCAKbAQIeARYhBA4tHmPiJT2F1/Az9/3NUj9cTr/A
AABVPQEAxKVxgeoASrp+zGIoPSLj0U7GqhU3nkIzCasScXQ+4+gBAODmc5N5ntUz
X18tPPRxd3GYKJ8myMD/yiyXq1BcS0oDtCBUb2JpYXMgWmVuayA8dC56ZW5rQGZh
bWVkbHkuY29tPojUBBMWCgCGBYJmgstlBYkDwmcAAwsJBwkQ/c1SP1xOv8BHFAAA
AAAAHgAgc2FsdEBub3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3JnivUMtaO3DMeiAOj0
BVlUSLZwGeciyXl/P/kE4nyE0u4DFQoIApkBApsBAh4BFiEEDi0eY+IlPYXX8DP3
/c1SP1xOv8AAALq+AQCL/Zs1mGffcnF1/hkslopa84A2Ib4vKIFndPietvF7ZwD+
OQtflzM8x4mLLXbvR3sRKQy5eENU9rGzx1IShdLLIQy4MwRmgstlFgkrBgEEAdpH
DwEBB0CE8ziQIhUpCV/NsaNBELz6l8Y+G/jO/CLHxxEXGG9i5IjGBBgWCgB4BYJm
gstlBYkDwmcACRD9zVI/XE6/wEcUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1
b2lhLXBncC5vcmfcQJ3TI7T+G9W3Wg91d85iuvlicMdGOBQkT7MY94/r2AKbIBYh
BA4tHmPiJT2F1/Az9/3NUj9cTr/AAAAZcAEAnrbiyEeJPvhqi9cTuRlH3+rWJ2vE
Ih2sOxhLZgc3iMgA/3OVQALa0qfdY3PmJbY+3G7rxoOMJjr19ecOC0FDPKsLuDME
ZoLLZRYJKwYBBAHaRw8BAQdA71KHIIo/8Sk+551dYYU0+0k86ruDGNHltsreaTfo
5NSJAYUEGBYKATcFgmaCy2UFiQPCZwAJEP3NUj9cTr/ARxQAAAAAAB4AIHNhbHRA
bm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZxxyfHEKsvHJrn4ckMh/V4WjAp4qJM8X
nyXQCg3QFoIJApsCvqAEGRYKAG8FgmaCy2UJEJU/+wIEZeaGRxQAAAAAAB4AIHNh
bHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZwS5Bbj6tOkj5FdOqBZdzzvBGSvL
jorvwO0T3PpdEwM1FiEEVl3r6hcbJlckxJ5wlT/7AgRl5oYAAMz8AP9hTUgZBttx
L+d7U0lEmQ3IrJIUmO3Skln3c81O3eSciQEA9Z6wvsln0m1+X1pzw9+Bok8sm9cE
Srn83k+f6yvyKggWIQQOLR5j4iU9hdfwM/f9zVI/XE6/wAAA6r8A/AzCWl6WBeLT
JMPUJ7zh0/ft3vVOzntdrxklLaCzDKLPAP922Zy4lx4Yx0tyQrq4Xy93UsHf/aA0
CDvNhhDzR4psDLg4BGaCy2USCisGAQQBl1UBBQEBB0A/pSpoXHBwp+gM6hNYy8av
rLXkVS4PZs+DJnN6+p7qBgMBCAeIxgQYFgoAeAWCZoLLZQWJA8JnAAkQ/c1SP1xO
v8BHFAAAAAAAHgAgc2FsdEBub3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3JncT7OedjM
0BwCBnSeEA1TjZ3jAoZnv1V7DB/aya0ie3cCmwwWIQQOLR5j4iU9hdfwM/f9zVI/
XE6/wAAAGqwBAKqIy5FoJFv4BOBcCQw9wx8dLHRREUNaPiTdmZNnrrTJAP4mUTBx
Idn4IqJ2MfqsSND5MM7gN1/ExauZzn3AIfdzDg==
=XlQJ
-----END PGP PUBLIC KEY BLOCK-----
"""
